	org 4096
	.core.CPC_PRIV_BASE EQU 40448
	.core.CPC_PRIV_SIZE EQU 1024
	.core.CPC_STACK_TOP EQU 42496
	.core.CPC_MEM_TOP EQU 42619
.core.__START_PROGRAM:
	di
	ld sp, .core.CPC_STACK_TOP
	call .core.CPC_INIT_FP_CALC
	call .core.CPC_INIT_SYSVARS
	jp .core.__MAIN_PROGRAM__
.core.ZXBASIC_USER_DATA:
	; Defines USER DATA Length in bytes
.core.ZXBASIC_USER_DATA_LEN EQU .core.ZXBASIC_USER_DATA_END - .core.ZXBASIC_USER_DATA
	.core.__LABEL__.ZXBASIC_USER_DATA_LEN EQU .core.ZXBASIC_USER_DATA_LEN
	.core.__LABEL__.ZXBASIC_USER_DATA EQU .core.ZXBASIC_USER_DATA
_x:
	DEFB 00, 00, 00, 00, 00
_y:
	DEFB 00, 00, 00, 00, 00
.core.ZXBASIC_USER_DATA_END:
.core.__MAIN_PROGRAM__:
	ld a, 081h
	ld de, 00040h
	ld bc, 00000h
	ld hl, _x
	call .core.__STOREF
	ld hl, _x + 4
	call .core.__FP_PUSH_REV
	ld a, 082h
	ld de, 00020h
	ld bc, 00000h
	call .core.__ADDF
	ld hl, _y
	call .core.__STOREF
	ld hl, _y + 4
	call .core.__FP_PUSH_REV
	ld a, 082h
	ld de, 00000h
	ld bc, 00000h
	call .core.__MULF
	ld hl, _y
	call .core.__STOREF
	ld a, (_y)
	ld de, (_y + 1)
	ld bc, (_y + 3)
	call .core.SIN
	ld hl, _y
	call .core.__STOREF
	ld a, (_y)
	ld de, (_y + 1)
	ld bc, (_y + 3)
	call .core.SQRT
	ld hl, _y
	call .core.__STOREF
	ld hl, 0
	ld b, h
	ld c, l
.core.__END_PROGRAM:
	rst 0
	;; --- end of user code ---
#line 1 "src/lib/arch/cpc/runtime/arith/addf.asm"
	; -----------------------------------------------------------------------
	; Amstrad CPC copy of zx48k/runtime/arith/addf.asm, generated by replacing every
; `rst 28h` with `rst 30h` (1-for-1, same opcode size): &0028 is the
	; firmware's RST 5 FIRM JUMP (not repointable), while RST 6 (&0030) is
	; the vector the Firmware Guide reserves for the user. RST 6 traps via
	; .core.__CPC_NOT_IMPLEMENTED until fp_calc.asm gets a real FP engine
; (TODO(cpc): Phase 3). Byte-for-byte zx48k's body otherwise -- see
	; tests/arch/cpc/test_cpc_fp_copies.py, which fails if it drifts.
#line 1 "src/lib/arch/cpc/runtime/fp_calc.asm"
	; -----------------------------------------------------------------------
	; Amstrad CPC -- placeholder floating point calculator
	;
	; The FP runtime files (arith/*.asm, negf.asm, cmp/*.asm, bool/*.asm,
	; math/*.asm) all execute `rst 30h` expecting it to behave like the ZX
	; Spectrum ROM's `rst 28h` CALCULATE entry. &0030 has no meaning to the
	; CPC firmware -- it is the one RST vector (RST 6) the Firmware Guide
	; reserves for the user -- so nothing places anything useful there unless
	; we do it ourselves.
	;
; This file is only a placeholder: .core.FP_CALC_ENTRY traps (hangs the
	; machine visibly) instead of running Spectrum calculator bytecode against
	; whatever happens to be at &0030. #init installs `jp .core.FP_CALC_ENTRY`
	; at &0030 at runtime, so RST 6 always reaches it.
	;
; TODO(cpc): replace with a real calculator, porting
	; src/lib/arch/zx81sd/runtime/fp_calc.asm (reimplements the ROM CALCULATE
	; engine using the same 5-byte float format and Lxxxx labels). Nothing
; outside this file needs to change then: the `rst 30h` call sites and
	; every other file that calls .core.FP_CALC_ENTRY will just start working.
#line 1 "src/lib/arch/cpc/runtime/stub.asm"
	; -----------------------------------------------------------------------
	; Amstrad CPC -- shared "not implemented yet" target
	;
	; Runtime files ported from zx48k that are not yet implemented for the
	; CPC (print.asm, plot.asm, error.asm, load.asm, ...) `jp
	; .core.__CPC_NOT_IMPLEMENTED` instead of leaving a dangling reference or
	; emitting incorrect Spectrum-specific code.
	;
	; This hangs the machine visibly (di + halt) rather than doing something
	; wrong silently. It is deliberately distinct from END's `rst 0` (a full
; firmware reset back to BASIC, see src/arch/cpc/backend/generic.py): a
	; reset would look like the program finished normally, which would hide
	; the bug this is meant to surface.
	    push namespace core
	; __CPC_NOT_IMPLEMENTED -- hangs the CPU. Nothing calls or returns from
	; this; it is a dead end reached only by a `jp` from an unfinished stub.
; Firmware entry called: none. Registers clobbered: none (never returns).
__CPC_NOT_IMPLEMENTED:
	    di
	    halt
	    pop namespace
#line 23 "src/lib/arch/cpc/runtime/fp_calc.asm"
	    push namespace core
	; CPC_RST6_VECTOR is the fixed address of the RST 6 vector itself, not a
; relocatable name: RST 6 always executes the 3 bytes at &0030, wherever
	; this file happens to be assembled into the program.
	CPC_RST6_VECTOR EQU $0030
; FP_CALC_ENTRY -- for now, traps. TODO(cpc): the real ROM-CALCULATE-alike
	; entry point, reached via `rst 30h` (opcode C7-equivalent at &0030..&0032
	; once CPC_INIT_FP_CALC has run).
FP_CALC_ENTRY:
	    jp __CPC_NOT_IMPLEMENTED
	; CPC_INIT_FP_CALC -- writes `jp FP_CALC_ENTRY` (bytes $C3, lo, hi) at
	; &0030-&0032, so every `rst 30h` in the FP runtime files reaches
	; FP_CALC_ENTRY above. &0000-&003F is ordinary RAM that user code can
	; write while the lower ROM is paged out; this must be done, and RST 6
	; must only ever be used, with interrupts disabled (the lower ROM pages
	; back in during firmware calls).
; Firmware entry called: none. Registers clobbered: AF, HL.
CPC_INIT_FP_CALC:
	    PROC
	    ld   hl, FP_CALC_ENTRY
	    ld   a, $C3        ; JP opcode
	    ld   (CPC_RST6_VECTOR), a
	    ld   (CPC_RST6_VECTOR + 1), hl
	    ret
	    ENDP
	    pop namespace
#line 11 "src/lib/arch/cpc/runtime/arith/addf.asm"
#line 1 "src/lib/arch/cpc/runtime/stackf.asm"
; Phase-1 stub for zx48k/runtime/stackf.asm (was: Spectrum ROM FP
	; calculator stack, via fixed entry points __FPSTACK_PUSH &2AB6 /
	; __FPSTACK_POP &2BF1). Those addresses don't exist on the CPC. Every
	; `rst 30h` FP runtime file and draw3.asm/io/sound/beep.asm call into
	; these, so they must all be defined even though real float support
	; doesn't exist yet (fp_calc.asm's own RST 6 target already traps first
	; anyway -- see its header).
; TODO(cpc): replace together with fp_calc.asm by porting zx81sd's own
	; relocatable stackf.asm, which needs no fixed ROM addresses.
	    push namespace core
__FPSTACK_PUSH:
	    jp __CPC_NOT_IMPLEMENTED
__FPSTACK_POP:
	    jp __CPC_NOT_IMPLEMENTED
__FPSTACK_PUSH2:
	    jp __CPC_NOT_IMPLEMENTED
__FPSTACK_I16:
	    jp __CPC_NOT_IMPLEMENTED
	    pop namespace
#line 13 "src/lib/arch/cpc/runtime/arith/addf.asm"
	; -------------------------------------------------------------
	; Floating point library using the FP ROM Calculator (ZX 48K)
	; All of them uses A EDCB registers as 1st paramter.
	; For binary operators, the 2n operator must be pushed into the
	; stack, in the order AF DE BC (F not used).
	;
	; Uses CALLEE convention
	; -------------------------------------------------------------
	    push namespace core
__ADDF:	; Addition
	    call __FPSTACK_PUSH2
	    ; ------------- ROM ADD
	    rst 30h
	    defb 0fh	; ADD
	    defb 38h;   ; END CALC
	    jp __FPSTACK_POP
	    pop namespace
#line 41 "tests/functional/arch/cpc/float_arith.bas"
#line 1 "src/lib/arch/cpc/runtime/arith/mulf.asm"
	; -----------------------------------------------------------------------
	; Amstrad CPC copy of zx48k/runtime/arith/mulf.asm, generated by replacing every
; `rst 28h` with `rst 30h` (1-for-1, same opcode size): &0028 is the
	; firmware's RST 5 FIRM JUMP (not repointable), while RST 6 (&0030) is
	; the vector the Firmware Guide reserves for the user. RST 6 traps via
	; .core.__CPC_NOT_IMPLEMENTED until fp_calc.asm gets a real FP engine
; (TODO(cpc): Phase 3). Byte-for-byte zx48k's body otherwise -- see
	; tests/arch/cpc/test_cpc_fp_copies.py, which fails if it drifts.
	; -------------------------------------------------------------
	; Floating point library using the FP ROM Calculator (ZX 48K)
	; All of them uses A EDCB registers as 1st paramter.
	; For binary operators, the 2n operator must be pushed into the
	; stack, in the order A DE BC.
	;
	; Uses CALLEE convention
	; -------------------------------------------------------------
	    push namespace core
__MULF:	; Multiplication
	    call __FPSTACK_PUSH2
	    ; ------------- ROM MUL
	    rst 30h
	    defb 04h	;
	    defb 38h;   ; END CALC
	    jp __FPSTACK_POP
	    pop namespace
#line 42 "tests/functional/arch/cpc/float_arith.bas"
#line 1 "src/lib/arch/cpc/runtime/bootstrap.asm"
	; -----------------------------------------------------------------------
	; Amstrad CPC bootstrap -- initialises the private runtime block's sysvars
	;
	; Registered with #init, so the compiler inserts
	; `call .core.CPC_INIT_SYSVARS` in the prologue (src/arch/cpc/backend/
	; main.py's emit_prologue()).
	;
	; Forced into every program via common.REQUIRES (backend/main.py's
; Backend.init()) rather than pulled in transitively: CPC_INIT_SYSVARS
	; must run even in programs with no PRINT/arrays/etc. that would
	; otherwise never #include sysvars.asm.
#line 1 "src/lib/arch/cpc/runtime/sysvars.asm"
	; -----------------------------------------------------------------------
	; Amstrad CPC system variables
	;
	; zx48k's own sysvars.asm and the runtime files ported from it hard-code
	; Spectrum sysvar addresses ($5C00-$5CB5), which are ordinary program RAM
	; on the CPC (inside the code/data area, $1000 up); using them as-is would
	; silently corrupt the compiled program. This file relocates them into the
	; private runtime block instead ($9E00-$A1FF, 1 KB -- see
	; .core.CPC_PRIV_BASE / CPC_PRIV_SIZE, emitted as EQUs by
	; src/arch/cpc/backend/main.py's prologue).
	;
	; This file only defines the *names and offsets*; CPC_INIT_SYSVARS
	; (bootstrap.asm) fills them in at runtime.
	;
; Layout ($9E00 + offset), all byte offsets from SYSVAR_BASE:
	;
	;   Offset  Size  Name               Note
	;   ------  ----  -----------------  ---------------------------------
	;   $00     2     CHARS              pointer to charset (8x8 cells)
	;   $02     2     UDG                pointer to UDG charset
	;   $04     2     COORDS             last PLOT/graphics coords (X,Y)
	;   $06     1     FLAGS2             screen flags (OVER/INVERSE/etc.)
	;   $07     1     ECHO_E             reserved, unused for now
	;   $08     2     DFCC               next screen bitmap addr for PRINT
	;   $0A     2     DFCCL              next screen attr addr for PRINT
	;   $0C     2     S_POSN             cursor position (H=row, L=column)
	;   $0E     1     ATTR_P             permanent attribute (INK/PAPER/etc.)
	;   $0F     1     ATTR_T             temporary attribute
	;   $10     1     P_FLAG             permanent print flags (OVER/INVERSE)
	;   $11     1     TV_FLAG            flags controlling output to screen
	;   $12     8     MEM0               scratch buffer, character bitmap gen.
	;   $1A     2     SCREEN_ADDR        pointer to the screen bitmap base
	;   $1C     2     SCREEN_ATTR_ADDR   placeholder -- the CPC has no
	;                                    per-cell attribute byte in memory
	;                                    the way the Spectrum does
	;   $1E     1     ERR_NR             error code (-1 = no error)
	;   $1F     2     FRAMES             software frame counter
	;   $21     2     RANDOM_SEED_LOW    RNG seed, low 16 bits
	;   $23     8     ARRAY_SCRATCH      LBOUND_PTR/UBOUND_PTR/RET_ADDR/
	;                                    TMP_ARR_PTR (2 bytes each)
	;   $2B     2     CHR_SCRATCH        return-address scratch for CHR$()
	;   $2D     4     DIVF_SCRATCH       TMP (2B) + ERR_SP (2B) for float
	;                                    division
;   $31     2     FW_BC              TODO(cpc): firmware BC' shadow, for
	;                                    a firmware call gate
;   $33     1     IN_FW              TODO(cpc): "inside firmware gate"
	;                                    flag
	;   $34     6     MODF16_SCRATCH     return addr + divider DE/HL for
	;                                    MOD16.16, kept separate from
	;                                    ARRAY_SCRATCH (the two must not alias)
	;   ------  ----
	;   $3A     (58 bytes used)
	;
	; $3A bytes used out of CPC_PRIV_SIZE ($400 = 1024). CPC_SYSVARS_USED
	; below lets it be compared against .core.CPC_PRIV_SIZE by eye whenever
	; this table grows.
	    push namespace core
	SYSVAR_BASE         EQU .core.CPC_PRIV_BASE
	CHARS               EQU SYSVAR_BASE + $00   ; DW -- pointer to charset (8x8 cells)
	UDG                 EQU SYSVAR_BASE + $02   ; DW -- pointer to UDG charset
	COORDS              EQU SYSVAR_BASE + $04   ; DW -- last PLOT/graphics coordinates (X,Y)
	FLAGS2              EQU SYSVAR_BASE + $06   ; DB -- screen flags (OVER/INVERSE/etc.)
	ECHO_E              EQU SYSVAR_BASE + $07   ; DB -- (reserved, unused for now)
	DFCC                EQU SYSVAR_BASE + $08   ; DW -- next screen bitmap address for PRINT
	DFCCL               EQU SYSVAR_BASE + $0A   ; DW -- next screen attribute address for PRINT
	S_POSN              EQU SYSVAR_BASE + $0C   ; DW -- cursor position (H=row, L=column)
	ATTR_P              EQU SYSVAR_BASE + $0E   ; DB -- permanent attribute (INK/PAPER/etc.)
	ATTR_T              EQU SYSVAR_BASE + $0F   ; DB -- temporary attribute
	P_FLAG              EQU SYSVAR_BASE + $10   ; DB -- permanent print flags (OVER/INVERSE)
	TV_FLAG             EQU SYSVAR_BASE + $11   ; DB -- flags controlling output to screen
	MEM0                EQU SYSVAR_BASE + $12   ; 8B -- scratch buffer for character bitmap generation
	SCREEN_ADDR         EQU SYSVAR_BASE + $1A   ; DW -- pointer to the screen bitmap base
	SCREEN_ATTR_ADDR    EQU SYSVAR_BASE + $1C   ; DW -- placeholder, see table above
	ERR_NR              EQU SYSVAR_BASE + $1E   ; DB -- error code (-1 = no error)
	FRAMES              EQU SYSVAR_BASE + $1F   ; DW -- software frame counter
	RANDOM_SEED_LOW     EQU SYSVAR_BASE + $21   ; DW -- RNG seed, low 16 bits
	ARRAY_SCRATCH       EQU SYSVAR_BASE + $23   ; 8B -- LBOUND_PTR/UBOUND_PTR/RET_ADDR/TMP_ARR_PTR
	CHR_SCRATCH         EQU SYSVAR_BASE + $2B   ; 2B -- return-address scratch for CHR$()
	DIVF_SCRATCH        EQU SYSVAR_BASE + $2D   ; 4B -- TMP (2B) + ERR_SP (2B) for float division
FW_BC               EQU SYSVAR_BASE + $31   ; 2B -- TODO(cpc): firmware BC' shadow
IN_FW               EQU SYSVAR_BASE + $33   ; 1B -- TODO(cpc): "inside firmware gate" flag
	MODF16_SCRATCH      EQU SYSVAR_BASE + $34   ; 6B -- return addr + divider DE/HL for MOD16.16
	CPC_SYSVARS_USED    EQU $3A                 ; bytes used above; compare by eye against
	                                             ; .core.CPC_PRIV_SIZE when this table grows
; --- Screen constants (CPC mode 1: 40 columns x 25 rows) ----------------
	; SCR_COLS keeps zx48k's own "columns + 1" convention (see zx48k's
; sysvars.asm: SCR_COLS EQU 33 for 32 visible columns).
	SCR_COLS            EQU 41      ; columns + 1 (40 columns visible)
	SCR_ROWS            EQU 25      ; rows visible
	SCR_SIZE            EQU (SCR_ROWS << 8) + SCR_COLS
	    pop namespace
#line 14 "src/lib/arch/cpc/runtime/bootstrap.asm"
	    push namespace core
	; CPC_INIT_SYSVARS -- zero-fills the private runtime block
	; ($9E00-$A1FF, .core.CPC_PRIV_BASE for .core.CPC_PRIV_SIZE bytes) and then
	; sets the few sysvars that need a non-zero default.
	;
; Firmware entry called: none (interrupts are off; this runs before any
	; firmware call is possible).
; Registers clobbered: AF, BC, DE, HL.
CPC_INIT_SYSVARS:
	    PROC
	    ; Zero-fill the whole private block first; sysvars set below simply
	    ; overwrite their own zeroed slot.
	    ld   hl, .core.CPC_PRIV_BASE
	    ld   (hl), 0
	    ld   de, .core.CPC_PRIV_BASE + 1
	    ld   bc, .core.CPC_PRIV_SIZE - 1
	    ldir
    ; ERR_NR: -1 means "no error", not 0 (matches the ZX Spectrum manual's
	    ; convention).
	    ld   a, $FF
	    ld   (ERR_NR), a
    ; SCREEN_ADDR: mode 1 screen base. SCREEN_ATTR_ADDR is left zeroed --
	    ; see the placeholder note in sysvars.asm.
	    ld   hl, $C000
	    ld   (SCREEN_ADDR), hl
	    ; Cursor at the top-left of the text window.
	    ld   hl, 0
	    ld   (S_POSN), hl
	    ret
	    ENDP
	    pop namespace
#line 43 "tests/functional/arch/cpc/float_arith.bas"
#line 1 "src/lib/arch/cpc/runtime/math/sin.asm"
	; -----------------------------------------------------------------------
	; Amstrad CPC copy of zx48k/runtime/math/sin.asm, generated by replacing every
; `rst 28h` with `rst 30h` (1-for-1, same opcode size): &0028 is the
	; firmware's RST 5 FIRM JUMP (not repointable), while RST 6 (&0030) is
	; the vector the Firmware Guide reserves for the user. RST 6 traps via
	; .core.__CPC_NOT_IMPLEMENTED until fp_calc.asm gets a real FP engine
; (TODO(cpc): Phase 3). Byte-for-byte zx48k's body otherwise -- see
	; tests/arch/cpc/test_cpc_fp_copies.py, which fails if it drifts.
	    push namespace core
SIN: ; Computes SIN using ROM FP-CALC
	    call __FPSTACK_PUSH
	    rst 30h	; ROM CALC
	    defb 1Fh
	    defb 38h ; END CALC
	    jp __FPSTACK_POP
	    pop namespace
#line 44 "tests/functional/arch/cpc/float_arith.bas"
#line 1 "src/lib/arch/cpc/runtime/math/sqrt.asm"
	; -----------------------------------------------------------------------
	; Amstrad CPC copy of zx48k/runtime/math/sqrt.asm, generated by replacing every
; `rst 28h` with `rst 30h` (1-for-1, same opcode size): &0028 is the
	; firmware's RST 5 FIRM JUMP (not repointable), while RST 6 (&0030) is
	; the vector the Firmware Guide reserves for the user. RST 6 traps via
	; .core.__CPC_NOT_IMPLEMENTED until fp_calc.asm gets a real FP engine
; (TODO(cpc): Phase 3). Byte-for-byte zx48k's body otherwise -- see
	; tests/arch/cpc/test_cpc_fp_copies.py, which fails if it drifts.
	    push namespace core
SQRT: ; Computes SQRT(x) using ROM FP-CALC
	    call __FPSTACK_PUSH
	    rst 30h	; ROM CALC
	    defb 28h ; SQRT
	    defb 38h ; END CALC
	    jp __FPSTACK_POP
	    pop namespace
#line 45 "tests/functional/arch/cpc/float_arith.bas"
#line 1 "src/lib/arch/zx48k/runtime/pushf.asm"
	; Routine to push Float pointed by HL
	; Into the stack. Notice that the hl points to the last
	; byte of the FP number.
	; Uses H'L' B'C' and D'E' to preserve ABCDEHL registers
	    push namespace core
__FP_PUSH_REV:
	    push hl
	    exx
	    pop hl
	    pop bc ; Return Address
	    ld d, (hl)
	    dec hl
	    ld e, (hl)
	    dec hl
	    push de
	    ld d, (hl)
	    dec hl
	    ld e, (hl)
	    dec hl
	    push de
	    ld d, (hl)
	    push de
	    push bc ; Return Address
	    exx
	    ret
	    pop namespace
#line 46 "tests/functional/arch/cpc/float_arith.bas"
#line 1 "src/lib/arch/zx48k/runtime/storef.asm"
	    push namespace core
__PISTOREF:	; Indect Stores a float (A, E, D, C, B) at location stored in memory, pointed by (IX + HL)
	    push de
	    ex de, hl	; DE <- HL
	    push ix
	    pop hl		; HL <- IX
	    add hl, de  ; HL <- IX + HL
	    pop de
__ISTOREF:  ; Load address at hl, and stores A,E,D,C,B registers at that address. Modifies A' register
	    ex af, af'
	    ld a, (hl)
	    inc hl
	    ld h, (hl)
	    ld l, a     ; HL = (HL)
	    ex af, af'
__STOREF:	; Stores the given FP number in A EDCB at address HL
	    ld (hl), a
	    inc hl
	    ld (hl), e
	    inc hl
	    ld (hl), d
	    inc hl
	    ld (hl), c
	    inc hl
	    ld (hl), b
	    ret
	    pop namespace
#line 47 "tests/functional/arch/cpc/float_arith.bas"
	END
