; -----------------------------------------------------------------------
; Amstrad CPC copy of zx48k/runtime/arith/mulf.asm, generated by replacing every
; `rst 28h` with `rst 30h` (1-for-1, same opcode size): &0028 is the
; firmware's RST 5 FIRM JUMP (not repointable), while RST 6 (&0030) is
; the vector the Firmware Guide reserves for the user, wired up to a real
; float engine (fp_calc.asm, ported from zx81sd). Byte-for-byte zx48k's body
; otherwise -- see tests/arch/cpc/test_cpc_fp_copies.py, which fails if it
; drifts.

#include once <fp_calc.asm>

#include once <stackf.asm>

; -------------------------------------------------------------
; Floating point library using the FP ROM Calculator (ZX 48K)
; All of them uses A EDCB registers as 1st paramter.
; For binary operators, the 2n operator must be pushed into the
; stack, in the order A DE BC.
;
; Uses CALLEE convention
; -------------------------------------------------------------

    push namespace core

__MULF:	; Multiplication
    call __FPSTACK_PUSH2

    ; ------------- ROM MUL
    rst 30h
    defb 04h	;
    defb 38h;   ; END CALC

    jp __FPSTACK_POP

    pop namespace
