; -----------------------------------------------------------------------
; Amstrad CPC copy of zx48k/runtime/math/tan.asm, generated by replacing every
; `rst 28h` with `rst 30h` (1-for-1, same opcode size): &0028 is the
; firmware's RST 5 FIRM JUMP (not repointable), while RST 6 (&0030) is
; the vector the Firmware Guide reserves for the user. RST 6 traps via
; .core.__CPC_NOT_IMPLEMENTED until fp_calc.asm gets a real FP engine
; (TODO(cpc): Phase 3). Byte-for-byte zx48k's body otherwise -- see
; tests/arch/cpc/test_cpc_fp_copies.py, which fails if it drifts.

#include once <fp_calc.asm>

#include once <stackf.asm>

    push namespace core

TAN: ; Computes TAN using ROM FP-CALC
    call __FPSTACK_PUSH

    rst 30h	; ROM CALC
    defb 21h ; TAN
    defb 38h ; END CALC

    jp __FPSTACK_POP

    pop namespace
