; -----------------------------------------------------------------------
; Amstrad CPC copy of zx48k/runtime/cmp/eqf.asm, generated by replacing every
; `rst 28h` with `rst 30h` (1-for-1, same opcode size): &0028 is the
; firmware's RST 5 FIRM JUMP (not repointable), while RST 6 (&0030) is
; the vector the Firmware Guide reserves for the user, wired up to a real
; float engine (fp_calc.asm, ported from zx81sd). Byte-for-byte zx48k's body
; otherwise -- see tests/arch/cpc/test_cpc_fp_copies.py, which fails if it
; drifts.

#include once <fp_calc.asm>

#include once <u32tofreg.asm>
#include once <ftou32reg.asm>
#include once <stackf.asm>

; -------------------------------------------------------------
; Floating point library using the FP ROM Calculator (ZX 48K)

; All of them uses C EDHL registers as 1st paramter.
; For binary operators, the 2n operator must be pushed into the
; stack, in the order BC DE HL (B not used).
;
; Uses CALLEE convention
; -------------------------------------------------------------


    push namespace core

__EQF:	; A = B
    call __FPSTACK_PUSH2

    ; ------------- ROM NOS-EQL
    ld b, 0Eh	; For comparison operators, OP must be in B also
    rst 30h
    defb 0Eh
    defb 38h;   ; END CALC

    call __FPSTACK_POP
    jp __FTOU8 ; Convert to 8 bits

    pop namespace
