; -----------------------------------------------------------------------
; Amstrad CPC copy of zx48k/runtime/cmp/ltf.asm, generated by replacing every
; `rst 28h` with `rst 30h` (1-for-1, same opcode size): &0028 is the
; firmware's RST 5 FIRM JUMP (not repointable), while RST 6 (&0030) is
; the vector the Firmware Guide reserves for the user. RST 6 traps via
; .core.__CPC_NOT_IMPLEMENTED until fp_calc.asm gets a real FP engine
; (TODO(cpc): Phase 3). Byte-for-byte zx48k's body otherwise -- see
; tests/arch/cpc/test_cpc_fp_copies.py, which fails if it drifts.

#include once <fp_calc.asm>

#include once <u32tofreg.asm>
#include once <ftou32reg.asm>
#include once <stackf.asm>

; -------------------------------------------------------------
; Floating point library using the FP ROM Calculator (ZX 48K)

; All of them uses A EDCB registers as 1st paramter.
; For binary operators, the 2n operator must be pushed into the
; stack, in the order A HL BC.
;
; Uses CALLEE convention
; -------------------------------------------------------------

    push namespace core

__LTF:	; A < B
    call __FPSTACK_PUSH2 ; Enters B, A

    ; ------------- ROM NOS-LESS
    ld b, 0Ch	; A > B (Operands stack-reversed)
    rst 30h
    defb 0Ch;	; A > B
    defb 38h;   ; END CALC

    call __FPSTACK_POP
    jp __FTOU8 ; Convert to 8 bits

    pop namespace
